sudo: required
services:
  - docker
before_install:
  - docker pull fr3akyphantom/droid-builder:latest
before_script:
- cd $HOME && mkdir twrp
- wget -q https://github.com/PhantomZone54/twrp_sources_norepo/releases/download/v3.5.0_9-20210130/MinimalOmniRecovery-twrp-5.1-norepo-20210130.tzst -O $HOME/twrp.tzst
- tar -I zstd -xvf twrp.tzst --directory $HOME/twrp/ && rm twrp.tzst
script:
  - cd $HOME/twrp/ && https://github.com/BoonVed/acer-b3a20.git device/Acer/B3-A20
  - git clone https://github.com/TwrpBuilder/android_device_generic_twrpbuilder.git device/generic/twrpbuilder
  - rm -rf bootable/recovery && git clone https://github.com/omnirom/android_bootable_recovery.git bootable/recovery
  - |
    docker run --rm -i -v "$(pwd):/root/twrp/:rw,z" r3akyphantom/droid-builder bash << EOF

    cd /root/twrp/
    source build/envsetup.sh && lunch omni_B3-A20-eng && make -j16 recoveryimage
    exit
    EOF
after_success:
  - export version=$(cat bootable/recovery/variables.h | grep "define TW_MAIN_VERSION_STR" | cut -d '"' -f2)
  - cp $HOME/twrp/out/target/product/X100V6/recovery.img $HOME/twrp/TWRP-$version-X100V6-$(date +"%Y%m%d").img

deploy:
  skip_cleanup: true
  provider: releases
  api_key: "$GIT_OAUTH_TOKEN_TB"
  file_glob: true
  file: $HOME/twrp/*.img
  on:
    tags: false
    repo: BoonVed/acer-b3a20
    branch: master

branches:
  except:
    - /^(?i:untagged)-.*$/
